### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/replicate_ui#1]
We need to figure out what can be done for actions and VBO (I believe we should see "Replicate" as an action in the content menu, for example).

From @jenlampton on Zulip:

> we still have hook_action_info() but those actions are usually triggered now by VBO, trigger module was moved to contrib.

**Comment by laryn** [comment]
It seems like the Views `.inc` wasn't loading. [With this commit](https://github.com/backdrop-contrib/replicate_ui/commit/5a579adef3b4ccbf28fd4239e09cd8a58d085bce) I'm able to edit the admin content page and add a "Replicate" drop button:

![Screen Shot 2020-07-14 at 2 06 55 PM](https://user-images.githubusercontent.com/871421/87466416-d4632b00-c5db-11ea-8a01-a3a54755d421.jpg)

Next question is whether we can/should try to add that to the admin content page automatically or not...

**Comment by jenlampton** [comment]
> It seems like the Views .inc wasn't loading

Maybe it wasn't added to `hook_autoload_info()`? Or, I bet you fixed that already... :)

**Comment by laryn** [comment]
@jenlampton The `hook_autoload_info` is loading the class:

 - https://github.com/backdrop-contrib/replicate_ui/blob/1.x-1.x/replicate_ui.module#L260-L267

But the issue is that the `*.views.inc` file never got loaded. It loads if I just add a stand alone `module_load_include` call but I'm not sure that's the correct way to do it.

 - https://github.com/backdrop-contrib/replicate_ui/commit/5a579adef3b4ccbf28fd4239e09cd8a58d085bce

**Comment by laryn** [comment]
Going to leave as is for now since it's functional and can adjust later if there's a better way.
